language: swift
osx_image: xcode12.5

cache: bundler

jobs:
  include:
  - stage: build
    name: "Building framework"
    script: bundle exec fastlane build_framework ios_version:'14.5'

  - stage: build
    name: "Building example app"
    script: bundle exec fastlane build_example_app ios_version:'14.5'

  - stage: test
    name: "Running unit tests"
    script: bundle exec fastlane ios test device:'iPhone 11' ios_version:'14.5'
    after_success: bundle exec slather

  - stage: deploy_pod
    name: "Deploying pod to Trunk"
    script: bundle exec fastlane deploy_pod

stages:
- name: build
  if: (type = pull_request OR type = push) AND branch = master

- name: test
  if: (type = pull_request OR type = push) AND branch = master

- name: deploy_pod
  if: type = push AND tag IS present

after_script: bash Scripts/telegram_notification.sh
